---
# Local version of librespot Spotify Connect Client
- name: ensure librespot container is running
  hosts: localhost
  connection: local
  become: yes

  vars:
    container_state: running
    container_name: librespot
    container_image_list:
      - localhost/librespot_minimal
    #container_dir_config: pihole-etc
    #container_dir_data: pihole-dnsmasq.d
    container_dir_owner: 0
    container_dir_group: 0
    container_run_args: >-
      --rm
      -dt
      --net host
      --device=/dev/snd
      --tz=local
      -v "{{exported_container_volumes_basedir}}/{{container_dir_config}}:/etc/pihole:Z"
      -v "{{exported_container_volumes_basedir}}/{{container_dir_data}}:/etc/dnsmasq.d:Z"
      --hostname="{{ container_name}}.{{ my_domain }}"
      --memory=512M
    firewall_port_list:
      - 49999:49999/tcp
      #- ADD MDNS SERVICE HERE

  tasks:
  - include_vars: vars/main.yml

#  - name: ensure container files mount point on host
#    tags: mount
#    file:
#      path: "{{exported_container_volumes_basedir}}/{{ item }}"
#      owner: "{{ container_dir_owner }}"
#      group: "{{ container_dir_group }}"
#      state: directory
#      recurse: yes
#    with_items:
#      - "{{container_dir_config}}"
#      - "{{container_dir_data}}"

  - name: ensure container state
    tags: container
    import_role:
      name: ikke_t.podman_container_systemd
