---
# Learnings from: https://8gwifi.org/docs/podman-jenkins.jsp
- name: ensure jenkins container is running
  hosts: localhost
  connection: local

  vars:
    container_state: running
    container_name: jenkins
    container_image_list:
      #- jenkins-blueocean
      - docker.io/jenkinsci/blueocean:latest
    container_run_as_user: bblasco
    container_run_as_group: bblasco
    #container_dir_owner: 0
    #container_dir_group: 0
    container_run_args: >-
      --rm
      --detach
      -p 18080:8080/tcp
      -p 50000:50000/tcp
      -v jenkins-data:/var/jenkins_home
      -v jenkins-docker-certs:/certs/client:ro
      --tz=local
      --hostname="jenkins.{{ my_domain }}"
    firewall_port_list:
      - 18080:18080/tcp
      - 50000:50000/tcp


  tasks:
  - include_vars: vars/main.yml

  - name: ensure container state
    tags: container
    import_role:
      name: ikke_t.podman_container_systemd
